#!/usr/bin/env python3
"""Comprehensive extraction of all vocabulary from Koine-Fluency PDF"""

import json

sheets_data = {
    "sheets": [
        {
            "id": 1,
            "number": "01",
            "greek_title": "Τίτλος",
            "english_title": "Title & Contents",
            "category": "structure",
            "description": "Overview of the 20 wall sheets"
        },
        {
            "id": 2,
            "number": "02",
            "greek_title": "Τὰ Ἐρωτηματικά Α΄",
            "english_title": "Question Words I",
            "category": "interrogatives",
            "terms": [
                {"greek": "τίς; τί;", "english": "Who? Which one? (gen. τίνος, dat. τίνι, acc. τίνα)"},
                {"greek": "πόθεν;", "english": "From where?"},
                {"greek": "τί;", "english": "What? (neuter often means Why?)"},
                {"greek": "πῶς;", "english": "How?"},
                {"greek": "ποῦ;", "english": "Where?"},
                {"greek": "πότε;", "english": "When?"},
                {"greek": "ποῖ;", "english": "To where? Whither?"},
                {"greek": "διὰ τί;", "english": "Why? For what reason?"}
            ]
        },
        {
            "id": 3,
            "number": "03",
            "greek_title": "Τὰ Ἐρωτηματικά Β΄",
            "english_title": "Question Words II",
            "category": "interrogatives",
            "terms": [
                {"greek": "ποῖος, -α, -ον;", "english": "Of what kind? Which?"},
                {"greek": "πόσος, -η, -ον;", "english": "How much? How many?"},
                {"greek": "ποσάκις;", "english": "How often? How many times?"},
                {"greek": "πηλίκος, -η, -ον;", "english": "How big? How great?"},
                {"greek": "ποδαπός, -ή, -όν;", "english": "Of what country or sort?"},
                {"greek": "πότερον … ἤ;", "english": "Which of two? Whether ... or?"}
            ]
        },
        {
            "id": 4,
            "number": "04",
            "greek_title": "Χαιρετισμοί",
            "english_title": "Greetings & Courtesy",
            "category": "communication",
            "terms": [
                {"greek": "χαῖρε / χαίρετε", "english": "Hello, greetings (sg./pl.)"},
                {"greek": "εἰρήνη σοι / ὑμῖν", "english": "Peace to you (sg./pl.)"},
                {"greek": "ἀντιβολῶ / παρακαλῶ", "english": "Please, I beg you"},
                {"greek": "εὐχαριστῶ σοι", "english": "Thank you (lit. I give thanks to you)"},
                {"greek": "χάριν ἔχω σοι", "english": "I am grateful to you"},
                {"greek": "ὑγίαινε", "english": "Be well, goodbye"},
                {"greek": "ἔρρωσο / ἔρρωσθε", "english": "Farewell (sg./pl.)"},
                {"greek": "σύγγνωθί μοι", "english": "Excuse me, forgive me"},
                {"greek": "συγγνώμην αἰτοῦμαι", "english": "I ask your pardon"},
                {"greek": "ἀσπάζομαί σε", "english": "I greet you"},
                {"greek": "καλῶς ἥκεις", "english": "Welcome"},
                {"greek": "ὁ κύριος μετὰ σοῦ", "english": "The Lord be with you"},
                {"greek": "οὐδὲν πρᾶγμα", "english": "It's nothing, no trouble"},
                {"greek": "τί ὄνομά σοι;", "english": "What is your name?"},
                {"greek": "ὄνομά μοι …", "english": "My name is ..."},
                {"greek": "πῶς λέγεται _______ Ἑλληνιστί;", "english": "How is _____ said in Greek?"},
                {"greek": "πόθεν εἶ;", "english": "Where are you from?"},
                {"greek": "εἰμὶ ἀπὸ …", "english": "I am from ..."},
                {"greek": "πῶς ἔχεις;", "english": "How are you?"},
                {"greek": "καλῶς ἔχω", "english": "I am well"},
                {"greek": "κακῶς ἔχω", "english": "I am unwell"},
                {"greek": "μετρίως", "english": "So-so, moderately"},
                {"greek": "ναί", "english": "Yes"},
                {"greek": "οὔ / οὐχί", "english": "No"},
                {"greek": "οὐδαμῶς", "english": "By no means, not at all"},
                {"greek": "μάλιστα", "english": "Certainly, most of all"},
                {"greek": "ἴσως", "english": "Perhaps"},
                {"greek": "ἀληθῶς / ἀμήν", "english": "Truly, indeed"},
                {"greek": "καὶ σύ;", "english": "And you?"},
                {"greek": "εὖγε", "english": "Well done! Bravo!"},
                {"greek": "καλῶς", "english": "Good, fine, all right"},
                {"greek": "ὀρθῶς", "english": "Correctly, rightly"},
                {"greek": "Ἑλληνιστί", "english": "In Greek"},
                {"greek": "Ἀγγλιστί", "english": "In English"},
                {"greek": "Ἑβραϊστί", "english": "In Hebrew"},
                {"greek": "Ῥωμαϊστί", "english": "In Latin"},
                {"greek": "λέγε μοι Ἑλληνιστί", "english": "Say it to me in Greek"},
                {"greek": "μὴ λέγε Ἀγγλιστί", "english": "Don't speak English"},
                {"greek": "χαίρω ὅτι ὑγιαίνεις", "english": "I am glad you are well"},
                {"greek": "ὕπαγε εἰς εἰρήνην", "english": "Go in peace"},
                {"greek": "εἰς αὖθις", "english": "Until next time"}
            ]
        },
        {
            "id": 5,
            "number": "05",
            "greek_title": "Ἐν τῇ Σχολῇ Α΄",
            "english_title": "Classroom Questions",
            "category": "communication",
            "terms": [
                {"greek": "ἐρώτησιν ἔχω.", "english": "I have a question."},
                {"greek": "ἔξεστίν μοι ἐρωτῆσαι;", "english": "May I ask?"},
                {"greek": "ἐρωτῆσαί σέ τι βούλομαι.", "english": "I want to ask you something."},
                {"greek": "ἀπόκριναί μοι, ἀντιβολῶ.", "english": "Answer me, please."},
                {"greek": "λέγε φωνῇ μεγάλῃ.", "english": "Speak in a loud voice."},
                {"greek": "τίς ἀποκρίνεται;", "english": "Who is answering?"},
                {"greek": "μικρὸν ἀνάμεινον.", "english": "Wait a moment."},
                {"greek": "μὴ φοβοῦ, λέγε μόνον.", "english": "Don't be afraid — just speak."},
                {"greek": "αὖθις εἰπέ, ἀντιβολῶ.", "english": "Say it again, please."},
                {"greek": "πάλιν εἰπέ.", "english": "Repeat it."},
                {"greek": "βραδέως λέγε.", "english": "Speak slowly."},
                {"greek": "βραδύτερον, ἀντιβολῶ.", "english": "More slowly, please."},
                {"greek": "δῆλόν ἐστιν;", "english": "Is it clear?"},
                {"greek": "δῆλόν ἐστιν. / οὐ δῆλόν μοι.", "english": "It's clear. / It's not clear to me."},
                {"greek": "συνίετε;", "english": "Do you (all) understand?"},
                {"greek": "ὀρθῶς εἶπας.", "english": "You said it correctly."},
                {"greek": "ἡμάρτηκα· διόρθωσόν με.", "english": "I've made a mistake — correct me."},
                {"greek": "οὐ καταλαμβάνω.", "english": "I do not understand."},
                {"greek": "οὐ συνίημι. / οὐ νοῶ.", "english": "I don't comprehend."},
                {"greek": "οὔπω συνῆκα.", "english": "I haven't understood yet."},
                {"greek": "νῦν καταλαμβάνω!", "english": "Now I understand!"},
                {"greek": "τί σημαίνει τοῦτο;", "english": "What does this mean?"},
                {"greek": "τί ἐστι τὸ ῥῆμα τοῦτο;", "english": "What is this word?"},
                {"greek": "πῶς γράφεται;", "english": "How is it written / spelled?"},
                {"greek": "τί μέρος λόγου ἐστίν;", "english": "What part of speech is it?"},
                {"greek": "ἐν ποίᾳ πτώσει ἐστίν;", "english": "In what case is it?"},
                {"greek": "ἐν ποίῳ χρόνῳ;", "english": "In what tense?"},
                {"greek": "ποία ἔγκλισις; ποία διάθεσις;", "english": "What mood? What voice?"},
                {"greek": "ποῖον πρόσωπον καὶ ποῖος ἀριθμός;", "english": "What person and number?"},
                {"greek": "οὔπω νοεῖτε οὐδὲ συνίετε;", "english": "Don't you understand yet?"},
                {"greek": "οὐκ οἶδα. / οὐ γινώσκω.", "english": "I don't know."},
                {"greek": "ἐπελαθόμην.", "english": "I have forgotten."},
                {"greek": "τέλος ἔχει.", "english": "It is finished / that's the end."},
                {"greek": "ἀναπαυσώμεθα ὀλίγον.", "english": "Let us rest a little."},
                {"greek": "ἀρξώμεθα.", "english": "Let us begin."},
                {"greek": "ἄγωμεν.", "english": "Let's go / let's get on."},
                {"greek": "αὔριον πάλιν.", "english": "Again tomorrow."}
            ]
        },
        {
            "id": 6,
            "number": "06",
            "greek_title": "Ἐν τῇ Σχολῇ Β΄",
            "english_title": "Commands & Objects",
            "category": "communication",
            "terms": [
                {"greek": "ἄκουε! / ἀκούετε!", "english": "Listen! (sg./pl.)"},
                {"greek": "ἀναγίνωσκε! / ἀναγινώσκετε!", "english": "Read! (sg./pl.)"},
                {"greek": "ἀνάγνωθι τοῦτο", "english": "Read this"},
                {"greek": "λέγε! / λέγετε!", "english": "Speak! (sg./pl.)"},
                {"greek": "γράφε! / γράφετε!", "english": "Write! (sg./pl.)"},
                {"greek": "βλέπε! / ἴδε!", "english": "Look! See!"},
                {"greek": "μένε! / μένετε!", "english": "Stay! Wait! (sg./pl.)"},
                {"greek": "δεῦρο! / δεῦτε!", "english": "Come here! (sg./pl.)"},
                {"greek": "ἔγειρε! / ἀνάστηθι!", "english": "Get up! Rise! (sg.)"},
                {"greek": "κάθισον! / καθίσατε!", "english": "Sit down! (sg./pl.)"},
                {"greek": "σιώπα! / σιωπᾶτε!", "english": "Be quiet! (sg./pl.)"},
                {"greek": "δός μοι …", "english": "Give me ..."},
                {"greek": "δεῖξόν μοι …", "english": "Show me ..."},
                {"greek": "ἄνοιξον / κλεῖσον τὸ βιβλίον", "english": "Open / close the book"},
                {"greek": "μὴ λάλει!", "english": "Don't talk!"},
                {"greek": "ὁ διδάσκαλος", "english": "Teacher"},
                {"greek": "ὁ μαθητής, -οῦ", "english": "Student, disciple"},
                {"greek": "ἡ μαθήτρια", "english": "Female student"},
                {"greek": "ὁ γραμματεύς", "english": "Scribe, scholar"},
                {"greek": "ὁ ἑταῖρος / ὁ φίλος", "english": "Companion / friend"},
                {"greek": "ὁ ἀδελφός, ἡ ἀδελφή", "english": "Brother, sister"},
                {"greek": "ῥαββί", "english": "Rabbi, my teacher"},
                {"greek": "τὸ βιβλίον", "english": "Book, scroll"},
                {"greek": "ἡ βίβλος", "english": "Book"},
                {"greek": "ἡ γραφή", "english": "Writing, scripture"},
                {"greek": "τὸ γράμμα", "english": "Letter of the alphabet"},
                {"greek": "ὁ λόγος", "english": "Word, saying, discourse"},
                {"greek": "ὁ κάλαμος", "english": "Reed pen"},
                {"greek": "τὸ μέλαν", "english": "Ink"},
                {"greek": "ὁ πίναξ", "english": "Board, tablet, platter"},
                {"greek": "ἡ θύρα", "english": "Door"},
                {"greek": "ἡ καθέδρα", "english": "Seat, chair"},
                {"greek": "ἡ τράπεζα", "english": "Table"},
                {"greek": "ὁ λύχνος, ἡ λυχνία", "english": "Lamp, lampstand"},
                {"greek": "ἡ σχολή", "english": "School, lecture-hall"},
                {"greek": "ὧδε / ἐκεῖ", "english": "Here / there"},
                {"greek": "ἔσω / ἔξω", "english": "Inside / outside"},
                {"greek": "ἄνω / κάτω", "english": "Above / below"},
                {"greek": "ἐπὶ τῆς τραπέζης", "english": "On the table"},
                {"greek": "ὑπὸ τὴν κλίνην", "english": "Under the bed"},
                {"greek": "παρὰ τῇ θύρᾳ", "english": "Beside the door"},
                {"greek": "ἐν μέσῳ ἡμῶν", "english": "In our midst"}
            ]
        },
        {
            "id": 7,
            "number": "07",
            "greek_title": "Περὶ Τροφῆς",
            "english_title": "Eating & Drinking",
            "category": "daily-life",
            "terms": [
                {"greek": "πεινῶ.", "english": "I am hungry."},
                {"greek": "διψῶ.", "english": "I am thirsty."},
                {"greek": "δός μοι τὸν ἄρτον, ἀντιβολῶ.", "english": "Give me the bread, please."},
                {"greek": "δός μοι ὕδωρ.", "english": "Give me water."},
                {"greek": "δός μοι πεῖν", "english": "Give me (something) to drink"},
                {"greek": "δός μοι τὸ ποτήριον.", "english": "Give me the cup."},
                {"greek": "δός μοι τὸν πίνακα.", "english": "Give me the plate."},
                {"greek": "δός μοι τὸ κοχλιάριον.", "english": "Give me the spoon."},
                {"greek": "δὸς αὐτῷ τὸ ἅλας.", "english": "Give him the salt."},
                {"greek": "οὐ πεινῶ ἔτι.", "english": "I am not hungry any more."},
                {"greek": "κεχόρτασμαι.", "english": "I am full, satisfied."},
                {"greek": "ἱκανῶς ἔχω.", "english": "I have had enough."},
                {"greek": "καλόν ἐστιν· ἡδύ ἐστιν.", "english": "It is good; it is delicious."},
                {"greek": "θέλω φαγεῖν.", "english": "I want to eat."},
                {"greek": "θέλω πιεῖν.", "english": "I want to drink."},
                {"greek": "οὐ θέλω φαγεῖν.", "english": "I do not want to eat."},
                {"greek": "μέλλω ἐσθίειν.", "english": "I am about to eat."},
                {"greek": "ὑπάγω φαγεῖν.", "english": "I am going off to eat."},
                {"greek": "λάβε καὶ φάγε.", "english": "Take and eat."},
                {"greek": "κλάσον τὸν ἄρτον.", "english": "Break the bread."},
                {"greek": "ἀνακλίθητε.", "english": "Recline at table."},
                {"greek": "νίψαι τὰς χεῖρας.", "english": "Wash your hands."},
                {"greek": "πλῦνον τὸ ποτήριον.", "english": "Wash the cup."},
                {"greek": "δεῦτε, φάγωμεν.", "english": "Come, let us eat."},
                {"greek": "τί ἐσθίομεν σήμερον;", "english": "What are we eating today?"},
                {"greek": "νηστεύω σήμερον.", "english": "I am fasting today."},
                {"greek": "εὐχαριστῶ σοι.", "english": "Thank you."},
                {"greek": "εὐχαριστήσωμεν πρὸ τοῦ φαγεῖν.", "english": "Let us give thanks before eating."},
                {"greek": "εὐλόγησον τὸν ἄρτον.", "english": "Bless the bread."},
                {"greek": "ἐσθίω, φάγομαι, ἔφαγον", "english": "I eat"},
                {"greek": "πίνω, πίομαι, ἔπιον", "english": "I drink"},
                {"greek": "γεύομαι", "english": "I taste"},
                {"greek": "χορτάζομαι", "english": "I am filled"},
                {"greek": "δειπνέω", "english": "I dine, take supper"},
                {"greek": "ἀριστάω", "english": "I take the morning meal"},
                {"greek": "νηστεύω", "english": "I fast"},
                {"greek": "εὐχαριστέω / εὐλογέω", "english": "I give thanks / bless"},
                {"greek": "κλάω", "english": "I break bread"},
                {"greek": "ἀνάκειμαι / κατάκειμαι", "english": "I recline at table"},
                {"greek": "διψάω / πεινάω", "english": "I thirst / I hunger"}
            ]
        },
        {
            "id": 8,
            "number": "08",
            "greek_title": "Τὰ Βρώματα καὶ τὰ Σκεύη",
            "english_title": "Food & Vessels",
            "category": "daily-life",
            "terms": [
                {"greek": "ὁ ἄρτος, -ου", "english": "Bread, loaf"},
                {"greek": "ὁ σῖτος, -ου", "english": "Wheat, grain"},
                {"greek": "ἡ ζύμη, -ης", "english": "Leaven"},
                {"greek": "τὸ ἄζυμον", "english": "Unleavened bread"},
                {"greek": "τὸ ἄλευρον", "english": "Flour"},
                {"greek": "ὁ κόκκος", "english": "Grain, seed"},
                {"greek": "τὸ ἔλαιον", "english": "Olive oil"},
                {"greek": "τὸ ὕδωρ, ὕδατος", "english": "Water"},
                {"greek": "ὁ οἶνος, -ου", "english": "Wine"},
                {"greek": "τὸ ὄξος, -ους", "english": "Sour wine, vinegar"},
                {"greek": "τὸ γάλα, γάλακτος", "english": "Milk"},
                {"greek": "τὸ μέλι, -ιτος", "english": "Honey"},
                {"greek": "τὸ ἅλας, -ατος", "english": "Salt"},
                {"greek": "ὁ ἰχθύς, -ύος", "english": "Fish"},
                {"greek": "τὸ ὀψάριον", "english": "Cooked fish, relish"},
                {"greek": "τὸ κρέας, -έως", "english": "Meat"},
                {"greek": "τὸ ᾠόν, -οῦ", "english": "Egg"},
                {"greek": "τὸ λάχανον", "english": "Vegetable, herb"},
                {"greek": "τὸ σῦκον / ἡ συκῆ", "english": "Fig / fig tree"},
                {"greek": "ἡ σταφυλή", "english": "Bunch of grapes"},
                {"greek": "ἡ ὄρυζα", "english": "Rice"},
                {"greek": "αἱ ἀκρίδες", "english": "Locusts"},
                {"greek": "τὸ βρῶμα, -ατος", "english": "Food"},
                {"greek": "ἡ τροφή, -ῆς", "english": "Nourishment"},
                {"greek": "τὸ ἄριστον", "english": "Morning / midday meal"},
                {"greek": "τὸ δεῖπνον", "english": "Dinner, banquet"},
                {"greek": "ἡ ἑορτή", "english": "Feast, festival"},
                {"greek": "τὸ πάσχα", "english": "Passover"},
                {"greek": "τὸ ποτήριον", "english": "Cup"},
                {"greek": "ὁ ξέστης", "english": "Pitcher, jug"},
                {"greek": "ὁ πίναξ, -ακος", "english": "Platter, plate"},
                {"greek": "τὸ τρύβλιον", "english": "Bowl, dish"},
                {"greek": "τὸ χαλκίον", "english": "Bronze vessel"},
                {"greek": "ἡ ὑδρία", "english": "Water jar"},
                {"greek": "τὸ κεράμιον", "english": "Earthen jar"},
                {"greek": "τὸ ἀγγεῖον", "english": "Container, vessel"},
                {"greek": "ὁ κόφινος / ἡ σπυρίς", "english": "Basket"},
                {"greek": "ὁ μόδιος", "english": "Measuring basket"},
                {"greek": "ἡ μάχαιρα", "english": "Knife, sword"},
                {"greek": "τὸ κοχλιάριον", "english": "Spoon"},
                {"greek": "τὸ μύστρον", "english": "Spoon, ladle"},
                {"greek": "ἡ τράπεζα", "english": "Table"},
                {"greek": "ὁ κλίβανος", "english": "Oven"},
                {"greek": "τὸ πῦρ, πυρός", "english": "Fire"}
            ]
        },
        {
            "id": 9,
            "number": "09",
            "greek_title": "Ἐν τῷ Κοιτῶνι",
            "english_title": "Going to Sleep",
            "category": "daily-life",
            "terms": [
                {"greek": "ὑπάγω καθεύδειν.", "english": "I am going to sleep."},
                {"greek": "μέλλω κοιμᾶσθαι.", "english": "I am about to go to bed."},
                {"greek": "εἰσέρχομαι εἰς τὸν κοιτῶνα.", "english": "I am going into the bedroom."},
                {"greek": "κοιμηθῶμεν ἤδη.", "english": "Let us go to sleep now."},
                {"greek": "ἔγειρε! / ἐγείρου!", "english": "Get up! (sg.)"},
                {"greek": "ἀνάστηθι.", "english": "Rise."},
                {"greek": "ἔγειρόν με πρωΐ.", "english": "Wake me early."},
                {"greek": "γρηγόρει! / γρηγορεῖτε!", "english": "Stay awake! (sg./pl.)"},
                {"greek": "ἔτι καθεύδεις;", "english": "Are you still sleeping?"},
                {"greek": "νυστάζω.", "english": "I am drowsy."},
                {"greek": "σβέσον τὸν λύχνον.", "english": "Put out the lamp."},
                {"greek": "κλεῖσον τὴν θύραν.", "english": "Shut the door."},
                {"greek": "ψῦχός ἐστιν.", "english": "It is cold."},
                {"greek": "καῦμά ἐστιν.", "english": "It is hot."},
                {"greek": "δός μοι ἄλλην στρωμνήν.", "english": "Give me another blanket."},
                {"greek": "ποῦ ἐστιν τὸ προσκεφάλαιόν μου;", "english": "Where is my pillow?"},
                {"greek": "ποῦ καθεύδω;", "english": "Where do I sleep?"},
                {"greek": "κοπιῶ· κέκμηκα.", "english": "I am weary; I am worn out."},
                {"greek": "οὐκ ἐδυνήθην καθεύδειν.", "english": "I could not sleep."},
                {"greek": "ἀναπαύσομαι ὀλίγον.", "english": "I will rest a little."},
                {"greek": "σίγα, ἀντιβολῶ· καθεύδουσιν.", "english": "Quiet, please — they are asleep."},
                {"greek": "εὖ καθεύδοις.", "english": "May you sleep well. (optative of wish)"},
                {"greek": "καλὴν νύκτα.", "english": "Good night."},
                {"greek": "ἡδεῖς ὄνειροι.", "english": "Sweet dreams."},
                {"greek": "εἰρήνη σοι εἰς τὴν νύκτα.", "english": "Peace to you through the night."},
                {"greek": "ἕως αὔριον.", "english": "Until tomorrow."},
                {"greek": "καθεύδω", "english": "I sleep"},
                {"greek": "κοιμάομαι", "english": "I fall asleep, lie down"},
                {"greek": "ὑπνόω", "english": "I sleep (classical)"},
                {"greek": "νυστάζω", "english": "I grow drowsy"},
                {"greek": "γρηγορέω", "english": "I stay awake, keep watch"},
                {"greek": "ἐγείρομαι", "english": "I get up"},
                {"greek": "ἀνίσταμαι", "english": "I rise"},
                {"greek": "ἀναπαύομαι", "english": "I rest"},
                {"greek": "διεγείρω", "english": "I wake someone up"}
            ]
        },
        {
            "id": 10,
            "number": "10",
            "greek_title": "Ἡ Νύξ",
            "english_title": "Night & Watches",
            "category": "daily-life",
            "terms": [
                {"greek": "ἡ κλίνη, -ης", "english": "Bed, couch"},
                {"greek": "ὁ κράβαττος, -ου", "english": "Mat, pallet"},
                {"greek": "ἡ κοίτη, -ης", "english": "Bed"},
                {"greek": "τὸ κλινίδιον", "english": "Little bed, stretcher"},
                {"greek": "τὸ προσκεφάλαιον", "english": "Pillow, cushion"},
                {"greek": "ἡ στρωμνή", "english": "Bedding, mattress, blanket"},
                {"greek": "τὸ στρῶμα", "english": "Mattress, coverlet"},
                {"greek": "ἡ χλαῖνα", "english": "Thick cloak used as blanket"},
                {"greek": "τὸ ἱμάτιον", "english": "Cloak — the poor man's blanket"},
                {"greek": "ἡ σινδών, -όνος", "english": "Linen sheet, wrap"},
                {"greek": "ὁ κοιτών, -ῶνος", "english": "Bedroom, sleeping chamber"},
                {"greek": "τὸ ταμεῖον", "english": "Inner room, private room"},
                {"greek": "τὸ ἀνάγαιον", "english": "Upper room"},
                {"greek": "τὸ ὑπερῷον", "english": "Upper storey"},
                {"greek": "ὁ οἶκος / ἡ οἰκία", "english": "House, household"},
                {"greek": "τὸ δῶμα", "english": "Roof, housetop"},
                {"greek": "ἡ θύρα / τὸ προαύλιον", "english": "Door / forecourt"},
                {"greek": "ἡ αὐλή", "english": "Courtyard"},
                {"greek": "ἡ νύξ, νυκτός", "english": "Night"},
                {"greek": "τὸ σκότος", "english": "Darkness"},
                {"greek": "ὁ ὕπνος, -ου", "english": "Sleep"},
                {"greek": "τὸ ἐνύπνιον", "english": "Dream"},
                {"greek": "τὸ ὄναρ", "english": "Dream (κατ' ὄναρ = in a dream)"},
                {"greek": "ὁ ἀλέκτωρ, -ορος", "english": "Rooster"},
                {"greek": "ἡ σελήνη / οἱ ἀστέρες", "english": "Moon / stars"},
                {"greek": "ὁ λύχνος / ἡ λυχνία", "english": "Lamp / lampstand"},
                {"greek": "ὁ ὄρθρος", "english": "Daybreak, dawn"},
                {"greek": "πρωΐ", "english": "Early, in the morning"},
                {"greek": "ὀψέ", "english": "Evening (c. 6–9 p.m.)"},
                {"greek": "μεσονύκτιον", "english": "Midnight (c. 9–12 p.m.)"},
                {"greek": "ἀλεκτοροφωνία", "english": "Cockcrow (c. 12–3 a.m.)"},
                {"greek": "στρώννυμι", "english": "I spread, make a bed"},
                {"greek": "νυκτός", "english": "By night (genitive of time)"}
            ]
        },
        {
            "id": 11,
            "number": "11",
            "greek_title": "Τὰ Μέρη τοῦ Λόγου Α΄",
            "english_title": "Parts of Speech I",
            "category": "grammar",
            "terms": [
                {"greek": "ἡ περίοδος", "english": "The sentence"},
                {"greek": "τὸ ῥῆμα", "english": "The verb"},
                {"greek": "τὸ ὄνομα", "english": "The noun"},
                {"greek": "τὸ ἐπίθετον", "english": "The adjective"}
            ]
        },
        {
            "id": 12,
            "number": "12",
            "greek_title": "Τὰ Μέρη τοῦ Λόγου Β΄",
            "english_title": "Parts of Speech II",
            "category": "grammar",
            "terms": [
                {"greek": "ἡ ἀντωνυμία", "english": "The pronoun"},
                {"greek": "ἡ πρόθεσις", "english": "The preposition"},
                {"greek": "τὸ ἄρθρον", "english": "The article"},
                {"greek": "τὸ ἐπίρρημα", "english": "The adverb"}
            ]
        },
        {
            "id": 13,
            "number": "13",
            "greek_title": "Τὰ Μέρη τοῦ Λόγου Γ΄",
            "english_title": "Parts of Speech III",
            "category": "grammar",
            "terms": [
                {"greek": "ὁ σύνδεσμος", "english": "The conjunction"},
                {"greek": "ἡ μετοχή", "english": "The participle"},
                {"greek": "τὸ ἀπαρέμφατον", "english": "The infinitive"},
                {"greek": "τὸ ἐπιφώνημα", "english": "The interjection"}
            ]
        },
        {
            "id": 14,
            "number": "14",
            "greek_title": "Ἡ Πτῶσις",
            "english_title": "The Cases",
            "category": "grammar",
            "terms": [
                {"greek": "ἡ ὀνομαστική", "english": "The nominative"},
                {"greek": "ἡ γενική", "english": "The genitive"},
                {"greek": "ἡ δοτική", "english": "The dative"},
                {"greek": "ἡ αἰτιατική", "english": "The accusative"},
                {"greek": "ἡ κλητική", "english": "The vocative"}
            ]
        },
        {
            "id": 15,
            "number": "15",
            "greek_title": "Τὸ Γένος καὶ ὁ Ἀριθμός",
            "english_title": "Gender & Number",
            "category": "grammar",
            "terms": [
                {"greek": "τὸ ἀρσενικόν", "english": "Masculine"},
                {"greek": "τὸ θηλυκόν", "english": "Feminine"},
                {"greek": "τὸ οὐδέτερον", "english": "Neuter"},
                {"greek": "ὁ ἑνικός", "english": "Singular"},
                {"greek": "ὁ δυϊκός", "english": "Dual"},
                {"greek": "ὁ πληθυντικός", "english": "Plural"}
            ]
        },
        {
            "id": 16,
            "number": "16",
            "greek_title": "Ὁ Χρόνος",
            "english_title": "The Tenses",
            "category": "grammar",
            "terms": [
                {"greek": "ὁ ἐνεστώς", "english": "The present"},
                {"greek": "ὁ μέλλων", "english": "The future"},
                {"greek": "ὁ ἀόριστος", "english": "The aorist"},
                {"greek": "ὁ ἐπὶ τέλει", "english": "The perfect"},
                {"greek": "ὁ ὑπερσυντέλικος", "english": "The pluperfect"}
            ]
        },
        {
            "id": 17,
            "number": "17",
            "greek_title": "Ἡ Διάθεσις",
            "english_title": "The Voices",
            "category": "grammar",
            "terms": [
                {"greek": "ἡ ἐνεργητική", "english": "The active voice"},
                {"greek": "ἡ μέση", "english": "The middle voice"},
                {"greek": "ἡ παθητική", "english": "The passive voice"}
            ]
        },
        {
            "id": 18,
            "number": "18",
            "greek_title": "Ἡ Ἔγκλισις",
            "english_title": "The Moods",
            "category": "grammar",
            "terms": [
                {"greek": "ἡ ὁριστική", "english": "The indicative"},
                {"greek": "ἡ ὑποτακτική", "english": "The subjunctive"},
                {"greek": "ἡ προστακτική", "english": "The imperative"},
                {"greek": "ἡ εὐκτική", "english": "The optative"}
            ]
        },
        {
            "id": 19,
            "number": "19",
            "greek_title": "Τὸ Πρόσωπον",
            "english_title": "Person & Sentence",
            "category": "grammar",
            "terms": [
                {"greek": "τὸ πρῶτον πρόσωπον", "english": "First person"},
                {"greek": "τὸ δεύτερον πρόσωπον", "english": "Second person"},
                {"greek": "τὸ τρίτον πρόσωπον", "english": "Third person"}
            ]
        },
        {
            "id": 20,
            "number": "20",
            "greek_title": "Πῶς Δεῖ Μελετᾶν",
            "english_title": "How to Drill",
            "category": "drilling",
            "description": "Five techniques for building active fluency"
        }
    ]
}

# Write to JSON file
from pathlib import Path
output_path = Path("src/data/sheets.json")
output_path.parent.mkdir(parents=True, exist_ok=True)

with open(output_path, "w", encoding="utf-8") as f:
    json.dump(sheets_data, f, ensure_ascii=False, indent=2)

print(f"✓ Extracted comprehensive data for all 20 sheets")
print(f"✓ Total unique vocabulary items: {sum(len(s.get('terms', [])) for s in sheets_data['sheets'])}")
for sheet in sheets_data['sheets']:
    if sheet.get('terms'):
        print(f"  Sheet {sheet['number']}: {len(sheet['terms'])} terms")
